spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_prod
    username: sfg-prod-user
    password: Siavash9126397748!
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false